### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dohliam** [laviande22/korean-word-ipa-dictionary#1]
This is great -- I'd love to add your results to [ipa-dict](https://github.com/open-dict-data/ipa-dict), since we don't have Korean yet. Would it be possible to add a license to the repo? More specifically, is the data under the same license as Wiktionary (i.e., [CC BY-SA](https://creativecommons.org/licenses/by-sa/3.0/))?

Thanks!

**Comment by uniglot** [comment]
I'd love to! I didn't think about licenses when I made this repo, but I think I have to follow the same license as Wiktionary grants. Feel free to use the results under CC BY-SA!

**Comment by dohliam** [comment]
Excellent! Thanks so much for updating this :+1:
